import type { ModelCard } from "@/app/api/ai-news/route";

/**
 * Hand-curated free-tier models from providers without machine-readable catalogs.
 * Each entry includes verified free-tier details and canonical links.
 * Last verified: 2026-09-02
 */

export const STATIC_FREE_MODELS: ModelCard[] = [
  // Google Gemini (AI Studio)
  {
    id: "google/gemini-1.5-flash",
    name: "Gemini 1.5 Flash",
    provider: "Google",
    source: "gemini",
    contextLength: 1_048_576,
    free: true,
    freeTier: "quota",
    freeTierDetail: "1,500 req/day, 250k TPM, 1M context",
    createdAt: Date.parse("2024-05-14"),
    inputs: ["text", "image"],
    tags: ["vision", "fast", "long-ctx"],
    url: "https://ai.google.dev/gemini-api/docs/models/gemini-1.5-flash",
  },
  {
    id: "google/gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google",
    source: "gemini",
    contextLength: 2_097_152,
    free: true,
    freeTier: "quota",
    freeTierDetail: "50 req/day, 250k TPM, 2M context",
    createdAt: Date.parse("2024-02-15"),
    inputs: ["text", "image"],
    tags: ["vision", "long-ctx"],
    url: "https://ai.google.dev/gemini-api/docs/models/gemini-1.5-pro",
  },
  {
    id: "google/gemini-2.0-flash-exp",
    name: "Gemini 2.0 Flash Experimental",
    provider: "Google",
    source: "gemini",
    contextLength: 1_048_576,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier with rate limits, 1M context",
    createdAt: Date.parse("2024-12-11"),
    inputs: ["text", "image"],
    tags: ["vision", "fast", "long-ctx"],
    url: "https://ai.google.dev/gemini-api/docs/models/gemini-2.0-flash",
  },

  // Groq
  {
    id: "groq/llama-3.1-70b-versatile",
    name: "Llama 3.1 70B Versatile",
    provider: "Groq",
    source: "groq",
    contextLength: 131_072,
    free: true,
    freeTier: "quota",
    freeTierDetail: "30 RPM, 14,400 RPD, 131K context",
    createdAt: Date.parse("2024-07-23"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://console.groq.com/docs/models/llama-3.1-70b-versatile",
  },
  {
    id: "groq/llama-3.1-8b-instant",
    name: "Llama 3.1 8B Instant",
    provider: "Groq",
    source: "groq",
    contextLength: 131_072,
    free: true,
    freeTier: "quota",
    freeTierDetail: "30 RPM, 14,400 RPD, 131K context",
    createdAt: Date.parse("2024-07-23"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://console.groq.com/docs/models/llama-3.1-8b-instant",
  },
  {
    id: "groq/mixtral-8x7b-32768",
    name: "Mixtral 8x7B",
    provider: "Groq",
    source: "groq",
    contextLength: 32_768,
    free: true,
    freeTier: "quota",
    freeTierDetail: "30 RPM, 14,400 RPD, 32K context",
    createdAt: Date.parse("2024-02-26"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://console.groq.com/docs/models/mixtral-8x7b-32768",
  },
  {
    id: "groq/gemma-7b-it",
    name: "Gemma 7B IT",
    provider: "Groq",
    source: "groq",
    contextLength: 8_192,
    free: true,
    freeTier: "quota",
    freeTierDetail: "30 RPM, 14,400 RPD, 8K context",
    createdAt: Date.parse("2024-03-15"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://console.groq.com/docs/models/gemma-7b-it",
  },

  // GitHub Models
  {
    id: "github/gpt-4o",
    name: "GPT-4o",
    provider: "GitHub Models",
    source: "github",
    contextLength: 128_000,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier with rate limits",
    createdAt: Date.parse("2024-05-13"),
    inputs: ["text", "image"],
    tags: ["vision", "long-ctx"],
    url: "https://github.com/marketplace/models/azure-openai/gpt-4o",
  },
  {
    id: "github/gpt-4o-mini",
    name: "GPT-4o Mini",
    provider: "GitHub Models",
    source: "github",
    contextLength: 128_000,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier with rate limits",
    createdAt: Date.parse("2024-07-18"),
    inputs: ["text", "image"],
    tags: ["vision", "fast", "long-ctx"],
    url: "https://github.com/marketplace/models/azure-openai/gpt-4o-mini",
  },
  {
    id: "github/phi-3.5-mini",
    name: "Phi-3.5 Mini",
    provider: "GitHub Models",
    source: "github",
    contextLength: 128_000,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier with rate limits",
    createdAt: Date.parse("2024-08-20"),
    inputs: ["text"],
    tags: ["fast", "long-ctx"],
    url: "https://github.com/marketplace/models/microsoft/phi-3.5-mini",
  },

  // Cerebras
  {
    id: "cerebras/llama-3.1-70b",
    name: "Llama 3.1 70B (Cerebras)",
    provider: "Cerebras",
    source: "cerebras",
    contextLength: 8_192,
    free: true,
    freeTier: "quota",
    freeTierDetail: "~2,600 tok/s, generous free tier",
    createdAt: Date.parse("2024-08-27"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://cloud.cerebras.ai/models/llama-3.1-70b",
  },
  {
    id: "cerebras/llama-3.1-8b",
    name: "Llama 3.1 8B (Cerebras)",
    provider: "Cerebras",
    source: "cerebras",
    contextLength: 8_192,
    free: true,
    freeTier: "quota",
    freeTierDetail: "~2,600 tok/s, generous free tier",
    createdAt: Date.parse("2024-08-27"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://cloud.cerebras.ai/models/llama-3.1-8b",
  },

  // LLM7.io
  {
    id: "llm7/glm-4-9b",
    name: "GLM-4-9B",
    provider: "LLM7",
    source: "llm7",
    contextLength: 1_048_576,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 1M context, 16+ models available",
    createdAt: Date.parse("2024-10-01"),
    inputs: ["text"],
    tags: ["long-ctx"],
    url: "https://llm7.io/models/glm-4-9b",
  },
  {
    id: "llm7/qwen-2.5-7b",
    name: "Qwen 2.5 7B",
    provider: "LLM7",
    source: "llm7",
    contextLength: 1_048_576,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 1M context",
    createdAt: Date.parse("2024-10-01"),
    inputs: ["text"],
    tags: ["long-ctx", "fast"],
    url: "https://llm7.io/models/qwen-2.5-7b",
  },

  // Kilo Code
  {
    id: "kilo/llama-3.1-70b",
    name: "Llama 3.1 70B (Kilo)",
    provider: "Kilo Code",
    source: "kilo",
    contextLength: 1_048_576,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 1M context, 12+ models",
    createdAt: Date.parse("2024-11-01"),
    inputs: ["text"],
    tags: ["long-ctx"],
    url: "https://kilocode.ai/models",
  },

  // Z AI (GLM)
  {
    id: "zai/glm-4-flash",
    name: "GLM-4 Flash",
    provider: "Z AI",
    source: "zai",
    contextLength: 131_072,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 128K context",
    createdAt: Date.parse("2024-10-15"),
    inputs: ["text"],
    tags: ["fast", "long-ctx"],
    url: "https://z.ai/models/glm-4-flash",
  },
  {
    id: "zai/glm-4-air",
    name: "GLM-4 Air",
    provider: "Z AI",
    source: "zai",
    contextLength: 1_048_576,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 1M context",
    createdAt: Date.parse("2024-10-15"),
    inputs: ["text"],
    tags: ["long-ctx"],
    url: "https://z.ai/models/glm-4-air",
  },

  // OVHcloud (EU/GDPR)
  {
    id: "ovh/mixtral-8x7b",
    name: "Mixtral 8x7B (OVHcloud)",
    provider: "OVHcloud",
    source: "ovh",
    contextLength: 32_768,
    free: true,
    freeTier: "quota",
    freeTierDetail: "EU-hosted, GDPR compliant, free tier",
    createdAt: Date.parse("2024-09-01"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://www.ovhcloud.com/en-gb/ai/ai-endpoints/",
  },

  // DeepSeek
  {
    id: "deepseek/deepseek-chat",
    name: "DeepSeek V3",
    provider: "DeepSeek",
    source: "deepseek",
    contextLength: 128_000,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier with rate limits",
    createdAt: Date.parse("2024-12-26"),
    inputs: ["text"],
    tags: ["fast", "long-ctx"],
    url: "https://platform.deepseek.com/api-docs",
  },
  {
    id: "deepseek/deepseek-reasoner",
    name: "DeepSeek R1",
    provider: "DeepSeek",
    source: "deepseek",
    contextLength: 64_000,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier with rate limits, reasoning model",
    createdAt: Date.parse("2025-01-20"),
    inputs: ["text"],
    tags: ["reasoning", "long-ctx"],
    url: "https://platform.deepseek.com/api-docs",
  },

  // SiliconFlow (CN)
  {
    id: "siliconflow/qwen-2.5-72b",
    name: "Qwen 2.5 72B (SiliconFlow)",
    provider: "SiliconFlow",
    source: "siliconflow",
    contextLength: 131_072,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 128K context",
    createdAt: Date.parse("2024-11-15"),
    inputs: ["text"],
    tags: ["long-ctx"],
    url: "https://cloud.siliconflow.cn/models",
  },

  // SambaNova
  {
    id: "sambanova/llama-3.1-70b",
    name: "Llama 3.1 70B (SambaNova)",
    provider: "SambaNova",
    source: "sambanova",
    contextLength: 8_192,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Fast inference, free tier",
    createdAt: Date.parse("2024-10-01"),
    inputs: ["text"],
    tags: ["fast"],
    url: "https://cloud.sambanova.ai/models",
  },

  // Nebius
  {
    id: "nebius/llama-3.1-70b",
    name: "Llama 3.1 70B (Nebius)",
    provider: "Nebius",
    source: "nebius",
    contextLength: 131_072,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 128K context",
    createdAt: Date.parse("2024-10-15"),
    inputs: ["text"],
    tags: ["long-ctx"],
    url: "https://studio.nebius.com/models",
  },

  // Nscale
  {
    id: "nscale/llama-3.1-70b",
    name: "Llama 3.1 70B (Nscale)",
    provider: "Nscale",
    source: "nscale",
    contextLength: 131_072,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 128K context",
    createdAt: Date.parse("2024-11-01"),
    inputs: ["text"],
    tags: ["long-ctx"],
    url: "https://console.nscale.com/models",
  },

  // AI21
  {
    id: "ai21/jamba-1.5-mini",
    name: "Jamba 1.5 Mini",
    provider: "AI21",
    source: "ai21",
    contextLength: 256_000,
    free: true,
    freeTier: "quota",
    freeTierDetail: "Free tier, 256K context, hybrid SSM-Transformer",
    createdAt: Date.parse("2024-08-29"),
    inputs: ["text"],
    tags: ["long-ctx", "fast"],
    url: "https://www.ai21.com/models/jamba-1.5-mini",
  },

  // xAI
  {
    id: "xai/grok-beta",
    name: "Grok Beta",
    provider: "xAI",
    source: "xai",
    contextLength: 131_072,
    free: true,
    freeTier: "trial",
    freeTierDetail: "$25/mo free credit during beta",
    createdAt: Date.parse("2024-11-04"),
    inputs: ["text"],
    tags: ["long-ctx"],
    url: "https://console.x.ai/",
  },
];

// Helper to get all static models
export async function fetchStaticCatalogModels(): Promise<ModelCard[]> {
  // Static data — no fetch needed, but keep async for uniform interface
  return STATIC_FREE_MODELS;
}